version: "2"
services:
  #api:
  #  build: ./system/api/
  #  expose:
  #    - 3000
  #    - 3306
  #  network_mode: host
  web:
    build: ./system/web/
    expose:
      - 80
      - 3306
    volumes:
      - ./system/web/html:/var/www/html
    network_mode: host
  cron:
    build: ./system/cron/
    network_mode: host
  mysql:
    network_mode: host
    build:
      context: ./mysql
      args:
        - MYSQL_DATABASE=default
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - mysql:/var/lib/mysql
      ports:
        - "3306:3306"

    