version: "2"
services:
  mysql:
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    volumes:
      - "./mysql-data:/var/lib/mysql"
      
      #- "./mysql/gold.sql:/docker-entrypoint-initdb.d/gold.sql"
      #- "./mysql/currency.sql:/docker-entrypoint-initdb.d/currency.sql"
      #- "./mysql/mpf.sql:/docker-entrypoint-initdb.d/mpf.sql"
      #- "./mysql/cronit.sql:/docker-entrypoint-initdb.d/cronit.sql" 
    environment:
      - "TZ=Asia/Shanghai"
      - "MYSQL_ROOT_PASSWORD=roota"
      
  web:
    build: "./web/"
    ports:
      - "90:80"
    volumes:
      - "./web/html:/var/www/html"
      
  cron:
    build: ./cron/
    volumes:
      - "./:/project"
