version: "2"
services:
      
  mysql-master:
    build: db/mysql/master
    ports:
    - "3307:3306"
    volumes:
    #- ./mysql-data:/var/lib/mysql
    - ./mysql-master_data:/var/lib/mysql
    - ./mysql-master_log:/var/log/mysql
      
    #- "./mysql/gold.sql:/docker-entrypoint-initdb.d/gold.sql"
    #- "./mysql/currency.sql:/docker-entrypoint-initdb.d/currency.sql"
    #- "./mysql/mpf.sql:/docker-entrypoint-initdb.d/mpf.sql"
    #- "./mysql/cronit.sql:/docker-entrypoint-initdb.d/cronit.sql" 
    env_file:
    - db/mysql/env.yml
    networks:
    - dockernet
    restart: on-failure

  php-apache1:
    build: php/apache
    ports:
    - "90:80"
    volumes:
    - ./php/files:/var/www
    networks:
    - dockernet
    restart: on-failure

  cron:
    build: ci/crontab
    volumes:
    - ./:/project
    networks:
    - dockernet
    restart: on-failure

networks:
  dockernet:
    external: true