version: "2"
services:
  mysql:
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      - "TZ=Asia/Shanghai"
      - "MYSQL_ROOT_PASSWORD=rootab"
      
  web:
    build: "./web/"
    ports:
      - "90:80"
    volumes:
      - "./web/html:/var/www/html"
      
  cron:
    build: ./cron/
    volumes:
      - "./:/project"
